Erroneous "print" changed to "echo"

diff --git a/bashdb-main.inc.in b/bashdb-main.inc.in
--- a/bashdb-main.inc.in
+++ b/bashdb-main.inc.in
@@ -10,7 +10,7 @@
 #   but WITHOUT ANY WARRANTY; without even the implied warranty of
 #   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 #   General Public License for more details.
-#   
+#
 #   You should have received a copy of the GNU General Public License
 #   along with this program; see the file COPYING.  If not, write to
 #   the Free Software Foundation, 59 Temple Place, Suite 330, Boston,
@@ -35,7 +35,7 @@ typeset _Dbg_shell_name=${_Dbg_shell##*/}  # Equivalent to basename(_Dbg_shell)
 typeset _Dbg_orig_0=$0
 
 # Equivalent to basename $0; the short program name
-typeset _Dbg_pname=${0##*/}  
+typeset _Dbg_pname=${0##*/}
 
 ## Stuff set by autoconf/configure ###
 typeset  prefix=@prefix@  # @PKGDATADIR@ often uses $prefix
@@ -48,11 +48,11 @@ typeset _Dbg_libdir=@PKGDATADIR@
 [[ -d $_Dbg_libdir ]] || _Dbg_libdir='.'
 
 typeset _Dbg_main="$_Dbg_libdir/dbg-main.sh"
-if [[ ! -r $_Dbg_main ]] ; then 
-  print "${_Dbg_pname}: Can't read debugger library file '${_Dbg_main}'."
-  print "${_Dbg_pname}: Perhaps @PACKAGE@ is installed wrong (if its installed)." >&2
-  print "${_Dbg_pname}: Try running @PACKAGE@ using -L (with a different directory)." >&2
-  print "${_Dbg_pname}: Run @PACKAGE@ --help for a list and explanation of options." >&2
+if [[ ! -r $_Dbg_main ]] ; then
+  echo "${_Dbg_pname}: Can't read debugger library file '${_Dbg_main}'."
+  echo "${_Dbg_pname}: Perhaps @PACKAGE@ is installed wrong (if its installed)." >&2
+  echo "${_Dbg_pname}: Try running @PACKAGE@ using -L (with a different directory)." >&2
+  echo "${_Dbg_pname}: Run @PACKAGE@ --help for a list and explanation of options." >&2
   exit 1
 fi
 
