A couple of messages were not going to stderr. Observation noticed by Christopher Barry.

diff --git a/bashdb.in b/bashdb.in
--- a/bashdb.in
+++ b/bashdb.in
@@ -74,7 +74,7 @@ done
 
 # All _Dbg_libdir setting done above. Have we succeeded? 
 if [[ ! -d $_Dbg_libdir ]] ; then 
-  echo "${_Dbg_pname}: Can't read debugger library directory '${_Dbg_libdir}'."
+  echo "${_Dbg_pname}: Can't read debugger library directory '${_Dbg_libdir}'." >&2
   echo "${_Dbg_pname}: Perhaps @PACKAGE@ is installed wrong (if its installed)." >&2
   echo "${_Dbg_pname}: Try running @PACKAGE@ using -L (with a different directory)." >&2
   echo "${_Dbg_pname}: Run @PACKAGE@ --help for a list and explanation of options." >&2
@@ -83,7 +83,7 @@ fi
 
 typeset _Dbg_main="$_Dbg_libdir/dbg-main.sh"
 if [[ ! -r $_Dbg_main ]] ; then 
-  print "${_Dbg_pname}: Can't read debugger library file '${_Dbg_main}'."
+  print "${_Dbg_pname}: Can't read debugger library file '${_Dbg_main}'." >&2
   print "${_Dbg_pname}: Perhaps @PACKAGE@ is installed wrong (if its installed)." >&2
   print "${_Dbg_pname}: Try running @PACKAGE@ using -L (with a different directory)." >&2
   print "${_Dbg_pname}: Run @PACKAGE@ --help for a list and explanation of options." >&2
