Rename a couple of variables to start with _Dbg_. Get closer to getting restart integration test working.

diff --git a/bashdb.in b/bashdb.in
--- a/bashdb.in
+++ b/bashdb.in
@@ -25,7 +25,7 @@
 # normally.
 
 [[ -z $_Dbg_ver ]] && typeset _Dbg_ver=\
-'$Id: bashdb.in,v 1.43 2008/10/02 02:37:31 rockyb Exp $'
+'$Id: bashdb.in,v 1.44 2008/10/03 08:57:25 rockyb Exp $'
 
 # This routine gets called via the -c or --command option and its sole
 # purpose is to capture the command string such as via "x $*" or 
@@ -112,7 +112,7 @@ fi
 # an effect.
 ((OPTLIND > 0)) && shift "$((OPTLIND - 1))"
     
-_source_file="$1"
+_Dbg_script_file="$1"
 shift
 
 if [[ ! -d $_Dbg_tmpdir ]] && [[ ! -w $_Dbg_tmpdir ]] ; then
@@ -124,11 +124,11 @@ fi
 # Note that this is called via bashdb rather than "bash --debugger"
 _Dbg_script=1
 
-if [[ ! -r "$_source_file" ]] && [[ -z $_Dbg_cmd ]] ; then
-  echo "${_Dbg_pname}: cannot read program to debug: ${_source_file}." >&2
+if [[ ! -r "$_Dbg_script_file" ]] && [[ -z $_Dbg_cmd ]] ; then
+  echo "${_Dbg_pname}: cannot read program to debug: ${_Dbg_script_file}." >&2
   exit 1
 else
-  typeset -r _Dbg_source_file=$(_Dbg_expand_filename $_source_file)
+  typeset -r _Dbg_Dbg_script_file=$(_Dbg_expand_filename $_Dbg_script_file)
 fi
 
 if ((_Dbg_linetrace)) ; then 
@@ -136,14 +136,14 @@ if ((_Dbg_linetrace)) ; then
   _Dbg_write_journal_eval "_Dbg_step_ignore=-1" 
   _Dbg_QUIT_ON_QUIT=1
 else 
-  # Set to skip over statements up to ". $_source_file"
+  # Set to skip over statements up to ". $_Dbg_script_file"
   _Dbg_write_journal_eval "_Dbg_step_ignore=4" 
 fi
 _Dbg_init_default_traps
 trap '_Dbg_debug_trap_handler 0 "$BASH_COMMAND" "$@"' DEBUG
 set -o functrace
 if [[ -z $_Dbg_cmd ]] ; then 
-  . "$_source_file"
+  . "$_Dbg_script_file"
 else 
   _Dbg_eval "$_Dbg_cmd"
 fi
