Change bashdb to use long options if getopt is around. bashdb now accepts --debugger to be compatible with bash --debugger.

diff --git a/bashdb.in b/bashdb.in
--- a/bashdb.in
+++ b/bashdb.in
@@ -1,5 +1,6 @@
+#!/bin/bash
 #!@BASH_PROG@
-#   Copyright (C) 2002, 2003, 2004, 2005  Rocky Bernstein rocky@panix.com
+#   Copyright (C) 2002, 2003, 2004, 2005, 2006  Rocky Bernstein rocky@panix.com
 #
 #   Bash is free software; you can redistribute it and/or modify it under
 #   the terms of the GNU General Public License as published by the Free
@@ -15,28 +16,44 @@
 #   with Bash; see the file COPYING.  If not, write to the Free Software
 #   Foundation, 59 Temple Place, Suite 330, Boston, MA 02111 USA.
 #
-# Alternate way to invoke debugger. bash --debugger however is preferred.
+
+# The alternate way to invoke debugger, "bash --debugger", has some
+# advantages: it sets $0 correctly and doesn't show this script in
+# the call trace. However the bash has been a bit inflexible and
+# quirky so sadly this script seems to be needed more than it would
+# normally.
 
 typeset _Dbg_ver=\
-'$Id: bashdb.in,v 1.1 2006/01/02 23:34:21 rockyb Exp $'
+'$Id: bashdb.in,v 1.2 2006/01/29 14:38:15 rockyb Exp $'
 
-declare -a _Dbg_script_args="$@"
+_Dbg_usage_long() {
+  printf "_Dbg_usage:
+    ${_Dbg_pname} [OPTIONS] <script_file>
 
-# Equivalent to basename $0; the short program name
-typeset _Dbg_pname=${0##*/}  
+Runs script_file under a debugger.
 
-# Show basename only in location listing. This is needed in regression tests
-typeset -i _Dbg_basename_only=${BASHDB_BASENAME_ONLY:-0}
+options: 
+    -B | --basename  basename only on source listings. 
+                     (Needed in regression tests)
+    -h | --help      print this help
+    -n | --no-init   Don't run initialization files
+    -c cmd | --command cmd
+                     Run this passed command of a script
+    -q | --quiet     Quiet. Do not print introductory and quiet messages.
+    -x cmdfile | --cmdfile
+                     execute debugger commands from cmdfile
+    -L libdir | --lib libdir
+                     set directory location of library helper file: $_Dbg_main
+                     The default directory is: $_Dbg_libdir
+    -T tmpdir | --temp
+                     set directory location for temporary files: $_Dbg_tmpdir
+    -t tty | --tty tty | --terminal tty
+                     set debugger terminal
+    -V | --version   show version number and no-warranty and exit.
+" 1>&2
+}
 
-typeset _Dbg_main=dbg-main.inc
-typeset _Dbg_libdir=@PKGDATADIR@
-typeset _Dbg_bindir=$(dirname $0)
-typeset _Dbg_tmpdir=/tmp
-
-typeset _Dbg_cmd='' # If command string given on command line, this is it.
-
-
-_Dbg_usage() {
+_Dbg_usage_shortt() {
   printf "_Dbg_usage:
     ${_Dbg_pname} [OPTIONS] <script_file>
 
@@ -57,6 +74,22 @@ options:
 " 1>&2
 }
 
+declare -a _Dbg_script_args="$@"
+
+# Equivalent to basename $0; the short program name
+typeset _Dbg_pname=${0##*/}  
+
+# Show basename only in location listing. This is needed in regression tests
+typeset -i _Dbg_basename_only=${BASHDB_BASENAME_ONLY:-0}
+
+typeset _Dbg_main=dbg-main.inc
+typeset _Dbg_libdir=@PKGDATADIR@
+typeset _Dbg_bindir=$(dirname $0)
+typeset _Dbg_tmpdir=/tmp
+
+typeset _Dbg_cmd='' # If command string given on command line, this is it.
+
+
 # What to set for location of helper routines? 
 if [[ ! -e $_Dbg_libdir/$_Dbg_main ]] ; then
   # Use bindir/../share as fallback
@@ -66,30 +99,80 @@ if [[ ! -e $_Dbg_libdir/$_Dbg_main ]] ; then
     fi
 fi
 
-while getopts BhnqVc:t:x:L:T: opt; do
-  case $opt in
-    B) _Dbg_basename_only=1 ;;
-    c) _Dbg_cmd="$OPTARG" ;;
-    h) _Dbg_usage; exit 100 ;;
-    n) _Dbg_no_init=1 ;;
-    q) _Dbg_quiet=1 ;;
-    x) BASHDB_INPUT="$BASHDB_INPUT $OPTARG" ;;  
-    L) _Dbg_libdir=$OPTARG ;;
-    T) _Dbg_tmpdir=$OPTARG ;;
-    t) 
-      if ! $(touch $OPTARG >/dev/null 2>/dev/null); then 
-	echo "${_Dbg_pname}: Can't access $OPTARG for writing."
-      elif [[ ! -w $OPTARG ]] ; then
-	echo "${_Dbg_pname}: terminal $OPTARG needs to be writable."
-      else
-	_Dbg_tty=$OPTARG
-      fi
-      ;;
-    V) show_version=1 ;;
-    *) _Dbg_usage; exit 2 ;;
+# Process using short or long options, depending on the availability
+# of getopt
+TEMP=`getopt -o testing 2>&1 >/dev/null`
+if [ 0 = $? ] ; then
+  # Process using long options
+  # Note that we use `"$@"' to let each command-line parameter expand to a 
+  # separate word. The quotes around `$@' are essential!
+  # We need TEMP as the `eval set --' would nuke the return value of getopt.
+  TEMP=`getopt -o BhnqVc:t:x:L:T:: \
+--long basename,command:,debugger,help,version,lib,no-init,quiet,temp:,terminal:,tty:: \
+     -n 'bashdb' -- "$@"`
+
+  if [ $? != 0 ] ; then 
+    echo "Use --help for option help. Terminating..." >&2 ; 
+    exit 1 ; 
+  fi
+  
+  # Note the quotes around `$TEMP': they are essential!
+  eval set -- "$TEMP"
+  
+  while true ; do
+    case $1 in
+      -B|--basename) _Dbg_basename_only=1 ;;
+      -c|--command) _Dbg_cmd="$2"; shift ;;
+      --debugger) ;;  # This option is for compatibility with bash --debugger
+      -h|--help) _Dbg_usage_long; exit 100 ;;
+      -L|--lib) _Dbg_libdir=$2; shift ;;
+      -n|--no-init) _Dbg_no_init=1 ;;
+      -q|--quiet) _Dbg_quiet=1 ;;
+      -x) BASHDB_INPUT="$BASHDB_INPUT $2"; shift ;;  
+      -T|--temp) _Dbg_tmpdir=$2; shift ;;
+      -t|--terminal|--tty) 
+	if ! $(touch $2 >/dev/null 2>/dev/null); then 
+	  echo "${_Dbg_pname}: Can't access $2 for writing."
+	elif [[ ! -w $2 ]] ; then
+	  echo "${_Dbg_pname}: terminal $2 needs to be writable."
+	else
+	  _Dbg_tty=$2 ;
+	fi
+	shift
+	;;
+      -V|--version) show_version=1 ;;
+      --) shift ; break ;;
+      *) _Dbg_usage_long; exit 2 ;;
   esac
-done
-shift $(($OPTIND - 1))
+    shift
+  done
+else 
+  # Process using short options
+  while getopts BhnqVc:t:x:L:T: opt; do
+    case $opt in
+      B) _Dbg_basename_only=1 ;;
+      c) _Dbg_cmd="$OPTARG" ;;
+      h) _Dbg_usage_short; exit 100 ;;
+      n) _Dbg_no_init=1 ;;
+      q) _Dbg_quiet=1 ;;
+      x) BASHDB_INPUT="$BASHDB_INPUT $OPTARG" ;;  
+      L) _Dbg_libdir=$OPTARG ;;
+      T) _Dbg_tmpdir=$OPTARG ;;
+      t) 
+	if ! $(touch $OPTARG >/dev/null 2>/dev/null); then 
+	  echo "${_Dbg_pname}: Can't access $OPTARG for writing."
+	elif [[ ! -w $OPTARG ]] ; then
+	  echo "${_Dbg_pname}: terminal $OPTARG needs to be writable."
+	else
+	  _Dbg_tty=$OPTARG
+	fi
+	;;
+      V) show_version=1 ;;
+      *) _Dbg_usage_short; exit 2 ;;
+    esac
+  done
+  shift $(($OPTIND - 1))
+fi
 
 [[ $# == 0 && -z $show_version && -z $_Dbg_cmd ]] && {
   echo "${_Dbg_pname}: Need to give a script name to debug."
@@ -126,7 +209,7 @@ _Dbg_script=1
 if [[ -z $_Dbg_quiet ]] ; then 
   echo "Bourne-Again Shell Debugger, release $_Dbg_release"
   cat <<EOF
-Copyright 2002, 2003, 2004 Rocky Bernstein
+Copyright 2002, 2003, 2004, 2006 Rocky Bernstein
 This is free software, covered by the GNU General Public License, and you are
 welcome to change it and/or distribute copies of it under certain conditions.
 
