Backport from current bash part 2

diff --git a/test/integration/check-common.sh.in b/test/integration/check-common.sh.in
--- a/test/integration/check-common.sh.in
+++ b/test/integration/check-common.sh.in
@@ -19,15 +19,38 @@ check_output() {
   return $?
 }
 
+# http://stackoverflow.com/questions/5451297/exit-code-when-crashed
+check_exit_status ()
+{
+    local status="$?";
+    local msg="";
+    local signal="";
+    if [ ${status} -ne 0 ]; then
+        if [ $((${status} < 128)) -ne 0 ]; then
+            msg="exit (${status})";
+        else
+            signal="$(builtin kill -l $((${status} - 128)) 2>/dev/null)";
+            if [ "$signal" ]; then
+                msg="kill -$signal$msg";
+            fi;
+        fi;
+        # want this to go to stdout to be captured
+        echo "INVESTIGATE EXIT FAILURE: [${status} => ${msg}]";
+    fi;
+    return 0
+}
+
+run_debugger_opts="-B -q --no-init --no-highlight"
 # Run the debugger on test program $1 with (optional) debugger options $2
 # using commandfile $3. We assume $TOP_BUILDDIR, $TOP_SRCDIR and
 # $TEST_NAME have been set previously
 run_debugger() {
   typeset debugged_script="$1"
-  typeset dbg_opts=${2:-"-L ${top_srcdir} -B -q --no-init"}
+  typeset dbg_opts=${2:-"-L ${top_srcdir} $run_debugger_opts"}
   [[ -z $short_test_name ]] && short_test_name=$TEST_NAME
   typeset cmdfile=${3:-"${top_srcdir}/test/data/${short_test_name}.cmd"}
   $SH -- ${top_builddir}/@PACKAGE@ $dbg_opts -x "$cmdfile" "$debugged_script" $ARGS
+  check_exit_status
 }
 
 ARGS=''
@@ -41,6 +64,7 @@ RIGHT_FILTERED_FILE="/tmp/${TEST_NAME}-filtered.right"
 run_test_check() {
     short_script_name=${1:-$TEST_NAME}
     short_test_name=${2:-$TEST_NAME}
+    debugged_script=${3:-"${top_srcdir}/test/example/${short_script_name}.sh"}
 
     # Reassign variables to allow overrides via the above parameters
     TEST_FILE="${top_builddir}/test/integration/${short_test_name}.check"
@@ -48,7 +72,6 @@ run_test_check() {
     TEST_FILTERED_FILE="/tmp/${short_test_name}-filtered.check"
     RIGHT_FILTERED_FILE="/tmp/${short_test_name}-filtered.right"
 
-    debugged_script="${top_srcdir}/test/example/${short_script_name}.sh"
     [[ ! -r $debugged_script ]] && \
 	debugged_script="${top_builddir}/test/example/${short_script_name}.sh"
     if [[ -z "$srcdir" ]] ; then
